import { defineType, defineField } from 'sanity'

/**
 * Build Guide Schema
 * 
 * Stores pre-calculated build recommendations generated by the build algorithm.
 * This schema is designed to be populated by automated scripts, not manual entry.
 * 
 * Data Flow:
 * 1. CSV files (characters.csv, weapons.csv) are updated
 * 2. Build algorithm script calculates optimal builds
 * 3. Script imports results into Sanity using this schema
 * 4. Frontend fetches and displays the pre-calculated data
 */

export const buildGuide = defineType({
  name: 'buildGuide',
  title: 'Build Guide',
  type: 'document',
  fields: [
    // ============================================
    // CORE REFERENCE
    // ============================================
    defineField({
      name: 'character',
      title: 'Character',
      type: 'reference',
      to: [{ type: 'character' }],
      validation: Rule => Rule.required(),
      description: 'Reference to the character this build guide is for'
    }),

    // ============================================
    // MODE-SPECIFIC BUILDS
    // ============================================
    defineField({
      name: 'soloMode',
      title: 'Solo/Ranking Mode Build',
      type: 'object',
      description: 'Optimized for solo play and ranking challenges',
      fields: [
        {
          name: 'weaponPairs',
          title: 'Recommended Weapon Pairs',
          type: 'array',
          description: 'Top 3 weapon combinations (Melee + Ranged)',
          of: [{
            type: 'object',
            fields: [
              {
                name: 'meleeWeapon',
                title: 'Melee Weapon',
                type: 'reference',
                to: [{ type: 'weapon' }],
                validation: Rule => Rule.required()
              },
              {
                name: 'rangedWeapon',
                title: 'Ranged Weapon',
                type: 'reference',
                to: [{ type: 'weapon' }],
                validation: Rule => Rule.required()
              },
              {
                name: 'pairScore',
                title: 'Pair Score',
                type: 'number',
                description: 'Combined compatibility score (0-1)',
                validation: Rule => Rule.min(0).max(1)
              },
              {
                name: 'reasoning',
                title: 'Why This Pair Works',
                type: 'object',
                fields: [
                  { name: 'en', title: 'English', type: 'text' },
                  { name: 'vi', title: 'Vietnamese', type: 'text' }
                ]
              }
            ],
            preview: {
              select: {
                melee: 'meleeWeapon.name.en',
                ranged: 'rangedWeapon.name.en',
                score: 'pairScore'
              },
              prepare({ melee, ranged, score }) {
                return {
                  title: `${melee || 'Unknown'} + ${ranged || 'Unknown'}`,
                  subtitle: `Score: ${score?.toFixed(2) || 'N/A'}`
                }
              }
            }
          }],
          validation: Rule => Rule.max(3)
        },
        {
          name: 'statPriority',
          title: 'Stat Priority',
          type: 'array',
          description: 'Recommended stat focus order',
          of: [{ type: 'string' }],
          options: {
            list: [
              { title: 'Critical Rate/Damage', value: 'crit' },
              { title: 'Attack Power', value: 'atk' },
              { title: 'Skill Damage', value: 'skilldmg' },
              { title: 'Cooldown Reduction', value: 'cdr' },
              { title: 'HP', value: 'hp' },
              { title: 'Defense', value: 'def' },
              { title: 'Attack Speed', value: 'aspd' }
            ]
          }
        },
        {
          name: 'playstyleTips',
          title: 'Playstyle Tips',
          type: 'object',
          fields: [
            { name: 'en', title: 'English', type: 'text' },
            { name: 'vi', title: 'Vietnamese', type: 'text' }
          ]
        }
      ]
    }),

    defineField({
      name: 'farmMode',
      title: 'Farm/Speedrun Mode Build',
      type: 'object',
      description: 'Optimized for farming and speedrunning content',
      fields: [
        {
          name: 'weaponPairs',
          title: 'Recommended Weapon Pairs',
          type: 'array',
          of: [{
            type: 'object',
            fields: [
              { name: 'meleeWeapon', type: 'reference', to: [{ type: 'weapon' }] },
              { name: 'rangedWeapon', type: 'reference', to: [{ type: 'weapon' }] },
              { name: 'pairScore', type: 'number' },
              {
                name: 'reasoning',
                type: 'object',
                fields: [
                  { name: 'en', type: 'text' },
                  { name: 'vi', type: 'text' }
                ]
              }
            ]
          }],
          validation: Rule => Rule.max(3)
        },
        {
          name: 'statPriority',
          type: 'array',
          of: [{ type: 'string' }],
          options: {
            list: [
              { title: 'AOE Damage', value: 'aoe' },
              { title: 'Duration', value: 'duration' },
              { title: 'Trigger Rate', value: 'trigger' },
              { title: 'Summon Power', value: 'summon' },
              { title: 'Attack Speed', value: 'aspd' },
              { title: 'Attack Power', value: 'atk' }
            ]
          }
        },
        {
          name: 'playstyleTips',
          type: 'object',
          fields: [
            { name: 'en', type: 'text' },
            { name: 'vi', type: 'text' }
          ]
        }
      ]
    }),

    defineField({
      name: 'bossMode',
      title: 'Boss/Single-Target Mode Build',
      type: 'object',
      description: 'Optimized for boss fights and single-target DPS',
      fields: [
        {
          name: 'weaponPairs',
          title: 'Recommended Weapon Pairs',
          type: 'array',
          of: [{
            type: 'object',
            fields: [
              { name: 'meleeWeapon', type: 'reference', to: [{ type: 'weapon' }] },
              { name: 'rangedWeapon', type: 'reference', to: [{ type: 'weapon' }] },
              { name: 'pairScore', type: 'number' },
              {
                name: 'reasoning',
                type: 'object',
                fields: [
                  { name: 'en', type: 'text' },
                  { name: 'vi', type: 'text' }
                ]
              }
            ]
          }],
          validation: Rule => Rule.max(3)
        },
        {
          name: 'statPriority',
          type: 'array',
          of: [{ type: 'string' }],
          options: {
            list: [
              { title: 'Critical Rate/Damage', value: 'crit' },
              { title: 'Attack Power', value: 'atk' },
              { title: 'Skill Damage', value: 'skilldmg' },
              { title: 'Cooldown Reduction', value: 'cdr' },
              { title: 'Stance Damage', value: 'stance' }
            ]
          }
        },
        {
          name: 'playstyleTips',
          type: 'object',
          fields: [
            { name: 'en', type: 'text' },
            { name: 'vi', type: 'text' }
          ]
        }
      ]
    }),

    // ============================================
    // TEAM COMPOSITIONS
    // ============================================
    defineField({
      name: 'teamCompositions',
      title: 'Recommended Team Compositions',
      type: 'array',
      description: 'Best team setups (Main + 2 AI Partners) for each mode',
      of: [{
        type: 'object',
        fields: [
          {
            name: 'mode',
            title: 'Game Mode',
            type: 'string',
            options: {
              list: [
                { title: 'Solo/Ranking', value: 'solo' },
                { title: 'Farm/Speedrun', value: 'farm' },
                { title: 'Boss/Single-Target', value: 'boss' }
              ]
            },
            validation: Rule => Rule.required()
          },
          {
            name: 'partner1',
            title: 'Partner 1 (AI)',
            type: 'reference',
            to: [{ type: 'character' }],
            validation: Rule => Rule.required()
          },
          {
            name: 'partner1MeleeWeapon',
            title: 'Partner 1 Best Melee Weapon',
            type: 'reference',
            to: [{ type: 'weapon' }],
            description: 'Recommended melee weapon for Partner 1'
          },
          {
            name: 'partner1RangedWeapon',
            title: 'Partner 1 Best Ranged Weapon',
            type: 'reference',
            to: [{ type: 'weapon' }],
            description: 'Recommended ranged weapon for Partner 1'
          },
          {
            name: 'partner2',
            title: 'Partner 2 (AI)',
            type: 'reference',
            to: [{ type: 'character' }],
            validation: Rule => Rule.required()
          },
          {
            name: 'partner2MeleeWeapon',
            title: 'Partner 2 Best Melee Weapon',
            type: 'reference',
            to: [{ type: 'weapon' }],
            description: 'Recommended melee weapon for Partner 2'
          },
          {
            name: 'partner2RangedWeapon',
            title: 'Partner 2 Best Ranged Weapon',
            type: 'reference',
            to: [{ type: 'weapon' }],
            description: 'Recommended ranged weapon for Partner 2'
          },
          {
            name: 'teamScore',
            title: 'Team Synergy Score',
            type: 'number',
            description: 'Overall team compatibility (0-1)',
            validation: Rule => Rule.min(0).max(1)
          },
          {
            name: 'synergies',
            title: 'Key Synergies',
            type: 'array',
            description: 'Why this team works well together',
            of: [{
              type: 'object',
              fields: [
                { name: 'type', title: 'Synergy Type', type: 'string' },
                {
                  name: 'description',
                  type: 'object',
                  fields: [
                    { name: 'en', type: 'text' },
                    { name: 'vi', type: 'text' }
                  ]
                }
              ]
            }]
          }
        ],
        preview: {
          select: {
            mode: 'mode',
            p1: 'partner1.name.en',
            p2: 'partner2.name.en',
            score: 'teamScore'
          },
          prepare({ mode, p1, p2, score }) {
            return {
              title: `${mode || 'Unknown'} Mode`,
              subtitle: `${p1 || '?'} + ${p2 || '?'} (${score?.toFixed(2) || 'N/A'})`
            }
          }
        }
      }]
    }),

    // ============================================
    // METADATA
    // ============================================
    defineField({
      name: 'algorithmVersion',
      title: 'Algorithm Version',
      type: 'string',
      description: 'Version of the build algorithm used to generate this data',
      initialValue: '2.2',
      readOnly: true
    }),

    defineField({
      name: 'lastCalculated',
      title: 'Last Calculated',
      type: 'datetime',
      description: 'When this build guide was last generated',
      readOnly: true
    }),

    defineField({
      name: 'autoGenerated',
      title: 'Auto-Generated',
      type: 'boolean',
      description: 'Whether this was generated by script (true) or manually created (false)',
      initialValue: true,
      readOnly: true
    }),

    defineField({
      name: 'manualOverrides',
      title: 'Manual Overrides',
      type: 'object',
      description: 'Optional manual adjustments by editors',
      fields: [
        {
          name: 'hasOverrides',
          title: 'Has Manual Overrides',
          type: 'boolean',
          initialValue: false
        },
        {
          name: 'notes',
          title: 'Override Notes',
          type: 'text',
          description: 'Why manual changes were made'
        }
      ]
    })
  ],

  preview: {
    select: {
      characterName: 'character.name.en',
      version: 'algorithmVersion',
      lastCalc: 'lastCalculated'
    },
    prepare({ characterName, version, lastCalc }) {
      return {
        title: `Build Guide: ${characterName || 'Unknown Character'}`,
        subtitle: `v${version || '?'} | Last updated: ${lastCalc ? new Date(lastCalc).toLocaleDateString() : 'Never'}`
      }
    }
  }
})

